# Generated by Django 6.0.3 on 2026-03-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ingradiente',
            new_name='ingrediente',
        ),
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Receita',
        ),
        migrations.RenameField(
            model_name='receitaingrediente',
            old_name='ingradiente',
            new_name='ingrediente',
        ),
    ]
